---
- hosts: all
  become: true
  tasks: 
  - name: update repo index
    apt:
      update_cache: yes

  - name: install apache2
    apt :
      name: apache2
  - name: install php support for apache2
    apt:
      name: libapache2-mod-php